import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import authRoutes from "./routes/auth.routes.js";
import postsRoutes from "./routes/posts.routes.js";
import commentsRoutes from "./routes/comments.routes.js";
import { withCookies } from "./middleware/auth.js";
import { errorHandler } from "./middleware/error.js";
const app = express();
app.use(helmet());
app.use(express.json());
app.use(withCookies);
app.use(morgan("dev"));
const allowed = process.env.CORS_ORIGIN ? process.env.CORS_ORIGIN.split(",") : ["http://localhost:3000"];
app.use(cors({ origin: allowed, credentials: true }));
app.get("/api/health", (_req, res) => res.json({ ok: true }));
app.use("/api/auth", authRoutes);
app.use("/api/posts", postsRoutes);
app.use("/api/comments", commentsRoutes);
app.use(errorHandler);
export default app;
